const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let preference='https://example.test/user/config/v/profile/manifest.json?v=mobile', requests=[], fixture, diagnostics=false, fetchFailure=null, responseStatus=200, logs=[];
const context={ $getUserPreference:(key)=>key === 'manifestUrl' ? preference : String(diagnostics), console:{error:(message)=>logs.push(message)}, fetch:async(url,options)=>{requests.push({url,options});if(fetchFailure) throw fetchFailure;return {ok:responseStatus===200,status:responseStatus,json:async()=> typeof fixture === 'function' ? fixture(url) : fixture};} };
vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/provider.js','utf8')+';globalThis.ProviderClass=Provider;',context);
(async()=>{
 const p=new context.ProviderClass();
 assert.equal(p.getSettings().episodeServers[0],'AIOStreams');
 const result=await p.search({media:{id:16498,englishTitle:'Attack on Titan'},query:''});assert.equal(result[0].id,'16498');
 fixture={data:{Media:{id:16498,idMal:16498,format:'TV',episodes:25,status:'FINISHED',title:{english:'Attack on Titan'}}}};
 const episodes=await p.findEpisodes('16498');assert.equal(episodes.length,25);assert.equal(new Set(episodes.map(e=>e.id)).size,25);
 fixture={streams:[{infoHash:'torrent-only'},{url:'https://cdn.test/a.mkv',name:'HEVC'},{url:'https://cdn.test/b.m3u8',name:'HLS',subtitles:[{url:'https://cdn.test/sub.vtt',lang:'eng'}]},{url:'https://cdn.test/c.mp4',behaviorHints:{proxyHeaders:{request:{Referer:'different'}}}}]};
 const server=await p.findEpisodeServer(episodes[0],'default');assert.equal(server.videoSources.length,2);assert.equal(server.videoSources[0].type,'unknown');assert.equal(server.videoSources[1].type,'m3u8');assert.equal(server.videoSources[1].subtitles[0].language,'eng');assert.equal(requests.at(-1).url,'https://example.test/user/config/v/profile/stream/series/mal%3A16498%3A1.json?v=mobile');
 fixture={data:{Media:{id:1,format:'TV',episodes:null,status:'RELEASING',nextAiringEpisode:{episode:9},title:{}}}};assert.equal((await p.findEpisodes('1')).length,8);
 fixture={data:{Media:{id:2,idMal:200,format:'MOVIE',episodes:1,status:'FINISHED',title:{english:'Film'}}}};const movies=await p.findEpisodes('2');fixture={streams:[{url:'https://cdn.test/movie.mp4'}]};await p.findEpisodeServer(movies[0],'default');assert(requests.at(-1).url.includes('/movie/mal%3A200.json'));
 fixture={streams:[{infoHash:'x'}]};await assert.rejects(()=>p.findEpisodeServer(movies[0],'default'),/no direct/);
 preference='';await assert.rejects(()=>p.findEpisodeServer(movies[0],'default'),/manifest/);
 preference='https://example.test/private/config/manifest.json';
 fixture=url=>url.includes('graphql.anilist.co') ? {data:{Media:{id:182205,idMal:59970,format:'TV',episodes:22,status:'RELEASING',title:{}}}} : {streams:[{url:'https://cdn.test/season4.mkv'}]};
 const start=requests.length;
 const mappedEpisodes=await p.findEpisodes('182205');
 assert.equal(requests.length,start+1,'normal episode lists only query metadata');
 assert.equal(JSON.parse(mappedEpisodes[1].id).mal,59970);
 assert(JSON.parse(requests.at(-1).options.body).query.includes('idMal'));
 await p.findEpisodeServer(mappedEpisodes[1],'default');
 assert(requests.at(-1).url.endsWith('/series/mal%3A59970%3A2.json'),'use the season MAL ID, not AniList ID');
 await p.findEpisodeServer({id:JSON.stringify({anilist:182205,episode:1,type:'series'})},'default');
 assert(requests.at(-1).url.endsWith('/series/mal%3A59970%3A1.json'),'resolve old cached episode IDs');
 fixture={data:{Media:{id:182205,idMal:null}}};
 await assert.rejects(()=>p.findEpisodeServer({id:JSON.stringify({anilist:182205,episode:1,type:'series'})},'default'),error=>typeof error==='string' && error.includes('no MyAnimeList mapping'));

 diagnostics=true;
 fixture=url=>url.includes('graphql.anilist.co') ? {data:{Media:{id:2,idMal:200,format:'MOVIE',episodes:1,status:'FINISHED',title:{english:'Film'}}}} : {streams:[]};
 assert.equal((await p.findEpisodes('2')).length,1,'failed diagnostics must preserve episodes');
 assert(logs.some(x=>x.includes('AIOStreams diagnostic (episode 1)') && x.includes('no direct')));
 diagnostics=false;
 responseStatus=403;
 await assert.rejects(()=>p.findEpisodeServer(movies[0],'default'),error=>typeof error==='string' && error.includes('HTTP 403'));
 responseStatus=200;
 fetchFailure=new Error('Network failed '+preference+' https://example.test/private/config/stream/movie/anilist:2.json');
 await assert.rejects(()=>p.findEpisodeServer(movies[0],'default'),error=>typeof error==='string' && error.includes('Network failed') && !error.includes('example.test') && !error.includes('/private/config'));
 assert(!logs.some(x=>x.includes('example.test') || x.includes('/private/config')));
 fetchFailure=null;
 await assert.rejects(()=>p.search({}),error=>typeof error==='string' && error.includes('AniList anime ID'));
 fixture={data:{Media:null}};
 await assert.rejects(()=>p.findEpisodes('2'),error=>typeof error==='string' && error.includes('AniList could not resolve'));
 console.log('PASS: diagnostics preserve lists, string rejections, HTTP status, network failures, URL redaction');
 console.log('PASS: configuration, exact AniList IDs, episodes, airing limits, movies, variant URLs, ordered sources, headers, subtitles, actionable errors');
})().catch(e=>{console.error(e);process.exitCode=1});
